
name: Actualizar Datos de Rayos GOES
on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta cada 10 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requisitos.txt

    - name: Ejecutar script del Satélite
      run: python script_satelite.py

    - name: Hacer Commit y Push del JSON actualizado
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add rayos.json
        git commit -m "Actualización automática de rayos en tiempo real" || exit 0
        git push
